//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PZone.Data.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PZone.Data.Localization.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя содержит недопустимые символы..
        /// </summary>
        internal static string PersonalDataValidationCharactersFirstName {
            get {
                return ResourceManager.GetString("PersonalDataValidationCharactersFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия содержит недопустимые символы..
        /// </summary>
        internal static string PersonalDataValidationCharactersLastName {
            get {
                return ResourceManager.GetString("PersonalDataValidationCharactersLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество содержит недопустимые символы..
        /// </summary>
        internal static string PersonalDataValidationCharactersMiddleName {
            get {
                return ResourceManager.GetString("PersonalDataValidationCharactersMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер содержит недопустимые символы. Разрешены только цифры..
        /// </summary>
        internal static string PersonalDataValidationCharactersNumberNumerics {
            get {
                return ResourceManager.GetString("PersonalDataValidationCharactersNumberNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия содержит недопустимые символы. Разрешены только цифры..
        /// </summary>
        internal static string PersonalDataValidationCharactersSerieNumerics {
            get {
                return ResourceManager.GetString("PersonalDataValidationCharactersSerieNumerics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пусто..
        /// </summary>
        internal static string PersonalDataValidationEmptyFirstName {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНН пустой..
        /// </summary>
        internal static string PersonalDataValidationEmptyInn {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptyInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия пуста..
        /// </summary>
        internal static string PersonalDataValidationEmptyLastName {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество пусто..
        /// </summary>
        internal static string PersonalDataValidationEmptyMiddleName {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptyMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер пустой..
        /// </summary>
        internal static string PersonalDataValidationEmptyNumber {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия пуста..
        /// </summary>
        internal static string PersonalDataValidationEmptySerie {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptySerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия и номер пусты..
        /// </summary>
        internal static string PersonalDataValidationEmptySerieNumber {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptySerieNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СНИЛС пустой..
        /// </summary>
        internal static string PersonalDataValidationEmptySnils {
            get {
                return ResourceManager.GetString("PersonalDataValidationEmptySnils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный формат ИНН..
        /// </summary>
        internal static string PersonalDataValidationIncorrectFormatInn {
            get {
                return ResourceManager.GetString("PersonalDataValidationIncorrectFormatInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный формат серии и номера. Серия и номер должны быть разделены одним пробелом..
        /// </summary>
        internal static string PersonalDataValidationIncorrectFormatSerieNumberSpace {
            get {
                return ResourceManager.GetString("PersonalDataValidationIncorrectFormatSerieNumberSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный формат СНИЛС..
        /// </summary>
        internal static string PersonalDataValidationIncorrectFormatSnils {
            get {
                return ResourceManager.GetString("PersonalDataValidationIncorrectFormatSnils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный ИНН..
        /// </summary>
        internal static string PersonalDataValidationIncorrectValueInn {
            get {
                return ResourceManager.GetString("PersonalDataValidationIncorrectValueInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный СНИЛС..
        /// </summary>
        internal static string PersonalDataValidationIncorrectValueSnils {
            get {
                return ResourceManager.GetString("PersonalDataValidationIncorrectValueSnils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина номера не равна {0} символам..
        /// </summary>
        internal static string PersonalDataValidationLengthNumberX {
            get {
                return ResourceManager.GetString("PersonalDataValidationLengthNumberX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина серии не равна {0} символам..
        /// </summary>
        internal static string PersonalDataValidationLengthSerieX {
            get {
                return ResourceManager.GetString("PersonalDataValidationLengthSerieX", resourceCulture);
            }
        }
    }
}
